### ISSUE TITLE
add support for other languages

### ISSUE THREAD

**Issue by netrox91** [Eisenhuth/dalamud-nael#1]
Hey Eisenhuth,
i appreciate your work here! Thanks for that :D

I have a question regarding using it with the german client.
i cloned the project and modified it with visual studio. I added the german quotes above the english ones starting at line 110 following. 

When i change the english quote that's used while calling the Test Function with my german quote it seems to work fine.
But in the actual raid it just doesn't change the quotes of nael in my chat :/ Am i missing something?

Thanks in advance! :D

Here's my change:
https://pastebin.com/raw/nazLCHC8

**Comment by Eisenhuth** [comment]
I coincidentally started working on adding support for other languages today.

The problem you're likely running into is how the game deals with unicode characters.

pulling an [example quote from xivapi](https://xivapi.com/NpcYell/6492?pretty=true) it ends up looking like this internally:
```json
"Text_de": "O roter Mond! F\u00fchre mich zur Herrschaft! ",
"Text_en": "O hallowed moon,\n\nshine you the iron path!",
"Text_fr": "\u00d4 lune! \u00c9claire la voie de la domination!",
"Text_ja": "\u6708\u3088\uff01\n\n\u9244\u306e\u8987\u9053\u3092\u7167\u3089\u305b\uff01",
```

**Comment by Eisenhuth** [comment]
@netrox91 I just pushed a version to the experimental branch that you could build - please let me know if it works for you
